# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "changelog.md"]
markdown: kramdown
highlighter: rouge
permalink: pretty

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: "HerVoice"

# Author/Organization info to be displayed in the templates
author:
  name: "Ilhan Birik Abdi"
  url: "https://ilha-an.github.io/"

# Set the baseurl to your repository name

baseurl: "ilha-an.github.io"

#destination for build site files
destination: "./_site"

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/logo.png  # You can replace this with your own logo
logoalt: "HerVoice Logo"

# Navigation
navigation:
- text: Home
  internal: true
  url: ./
- text: About
  internal: true
  url: about
- text: Contact
  internal: true
  url: contact

# Repo list (Optional)
repos:
- name: "HerVoice Project"
  description: "A platform for gender equity using AI."
  url: "https://github.com/Ilha-an/ilha-an.github.io

# Google Analytics (Optional)
google_analytics_ua: ""

# Style Variables
brand_color: "#DA253B"  # Customize this with your preferred brand color
